using System.Globalization;
using System.Text.RegularExpressions;
using Words.Core;

namespace Words.Lexicon.Building;

/// <summary>
/// Reads a word list generated by the ESDB customisation tool at app.aspell.net/create.
/// </summary>
/// <remarks>
/// The generated file opens with a header recording the exact parameters used, then a
/// blank line, then one entry per line. The header is how we recover a frequency signal:
/// the inline word list carries no per-entry score, but the sizes are cumulative supersets,
/// so an entry appearing in the size-35 list is far more common than one appearing only in
/// size 80. Generating every band and taking the smallest an entry appears in reconstructs
/// that gradient — see <see cref="ScoreForSize"/>.
/// </remarks>
public sealed partial class EsdbWordListReader : IWordListReader
{
    public string Name => "ESDB";

    public bool CanRead(IReadOnlyList<string> sampleLines) =>
        sampleLines.Any(line => line.Contains("app.aspell.net", StringComparison.OrdinalIgnoreCase));

    public IEnumerable<RawEntry> Read(TextReader reader)
    {
        ArgumentNullException.ThrowIfNull(reader);

        var size = ReadHeaderSize(reader);
        var score = ScoreForSize(size);

        while (reader.ReadLine() is { } line)
        {
            var entry = line.Trim();
            if (entry.Length == 0)
            {
                continue;
            }

            yield return new RawEntry(entry, score, Sources.Esdb, IsRacy: false);
        }
    }

    /// <summary>
    /// Consumes the header, returning the ESDB size band it declares. The header ends at
    /// the first blank line.
    /// </summary>
    private static int ReadHeaderSize(TextReader reader)
    {
        int? size = null;

        while (reader.ReadLine() is { } line)
        {
            if (line.Trim().Length == 0)
            {
                break;
            }

            var match = SizePattern().Match(line);
            if (match.Success)
            {
                size = int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
            }
        }

        return size ?? throw new InvalidDataException(
            "ESDB word list header did not declare a size. Regenerate it from app.aspell.net/create.");
    }

    /// <summary>
    /// Maps an ESDB size band onto the shared 0–100 scale. Smaller bands hold commoner
    /// words, so they score higher. The exact numbers are a judgement, not a measurement:
    /// they exist to order results sensibly, not to claim precision the source lacks.
    /// </summary>
    private static int ScoreForSize(int size) => size switch
    {
        <= 35 => 100,
        <= 50 => 90,
        <= 60 => 80,
        <= 70 => 65,
        <= 80 => 50,
        _ => 40,
    };

    [GeneratedRegex(@"^\s*Size:\s*(\d+)", RegexOptions.IgnoreCase)]
    private static partial Regex SizePattern();
}
