<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>words</AssemblyName>
    <RootNamespace>Words.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Words.Core/Words.Core.csproj" />
    <ProjectReference Include="../Words.LexiconBuilding/Words.LexiconBuilding.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
